name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --configuration Release

      - name: Verify path existence
        shell: pwsh
        run: |
          if (Test-Path -Path "./ApiNet.Tests/ApiNet.Tests.csproj") {
            Write-Host "File Exists."
          } else {
            Write-Host "File Does Not Exist."
          }

      - name: Finalize ApiNet.exe if running
        run: |
          taskkill /IM ApiNet.exe /F || echo "ApiNet.exe não encontrado"
       

      - name: Run tests
        run: dotnet test ./ApiNet.Tests/ApiNet.Tests.csproj --configuration Release --no-build --verbosity normal
