name: .NET CI

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'  # Versão do .NET que você está usando no projeto

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Run tests
        run:  dotnet test .\ApiNet.Tests\ApiNet.Tests.csproj --configuration Release
